services:
  recipemanagementsystem.api:
    image: ${DOCKER_REGISTRY-}recipemanagementsystemapi
    build:
      context: .
      dockerfile: RecipeManagementSystem.Api/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081" 
   
  recipemanagementsystem.client:
    image: ${DOCKER_REGISTRY-}recipemanagementsystemclient
    build:
      context: ../recipemanagementsystem.client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "https://localhost:8081"
    depends_on:
    - recipemanagementsystem.api